# Use official Node.js image
FROM node:23

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the project files
COPY . .

# Expose the port
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "start"]

